CREATE TABLE Loan
(
LoanNumber BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
LoanTypeNumber BIGINT FOREIGN KEY REFERENCES LoanType(LoanTypeNumber),
CopyNumber BIGINT FOREIGN KEY REFERENCES DVDCopy(CopyNumber),
MemberNumber BIGINT FOREIGN KEY REFERENCES Member(MemberNumber),
DateOut DATETIME,
DateDue DATETIME,
DateReturned DATETIME
)